config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :collections do
    resources :items
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :collection_items
  has_many :issues, through: :collection_items
end

app/models/collection_item.rb
class CollectionItem < ActiveRecord::Base
  belongs_to :collection
  belongs_to :issue
end

app/models/issue.rb
class Issue < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @collections = Collection.all
  end

  def show
    @collection = Collection.find(params[:id])
  end

  def new
    @collection = Collection.new
  end

  def create
    collection = Collection.create(collection_params)
    redirect_to collection_path(collection)
  end

  private
  def collection_params
    params.require(:collection).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @issues = Issue.all
    @collection = Collection.find(params[:collection_id])
    @item = CollectionItem.new
  end

  def create
    collection = Collection.find(params[:collection_item][:collection])
    issue = Issue.find(params[:collection_item][:issue])
    CollectionItem.create(issue: issue, collection: collection)
    redirect_to collection_path(collection)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/collections/index.html.erb
<ul style="margin-top: 21px">
  <% @collections.each do |collection| %>
    <li>
      <%= link_to collection.name, collection_path(collection) %>
    </li>
  <% end %>
</ul>

app/views/collections/new.html.erb
<h1>Create collection</h1>

<%= form_for(@collection, html: { role: "form", class: "form-horizontal" }) do |f| %>
  <div class="form-group">
    <div class="col-sm-7">
      <%= f.text_field :name, placeholder: "Collection name", class: "form-control" %>
    </div>
  </div>

  <div class="form-grup">
    <%= link_to "Cancel", root_path, class: "btn btn-default" %>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/collections/show.html.erb
<div class=row">
  <h1 class="col-sm-10"><%= @collection.name %></h1>
  <div class="col-sm-2" style="margin-top: 21px">
    <%= link_to "Add album", new_collection_item_path(@collection), class: "btn btn-primary"%>
  </div>
</div>

<div class=row">
  <div class="col-sm-12">
  <% @collection.issues.each do |issue| %>
    <%= image_tag(issue.cover_url, style: "margin: 10px") %>
  <% end %>
</div>
</div>

app/views/items/new.html.erb
<h1>Add Album</h1>

<% @issues.each do |issue| %>
  <%= form_for(@item) do |f| %>
    <%= f.hidden_field :collection, value: @collection.id %>
    <%= f.hidden_field :issue,      value: issue.id %>
    <span onclick="this.parentNode.submit()" style="float:left; margin: 10px">
      <%= image_tag(issue.cover_url) %>
    </span>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vinylcollections</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to  "VinylCollections", :root, class: "navbar-brand" %>
      </div>
    </div>
  </div>
  <div class="container" style="margin-top: 42px">
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron page-header">
  <h1>VinylCollections</h1>
  <p>Organize your collection in one place</p>
  <div class="row" style="margin-top: 42px">
    <div class="col-sm-6">
      <%= link_to "Create collection", new_collection_path, class: "btn btn-primary btn-lg" %>
    </div>
    <div class="col-sm-6">
      <%= link_to "View all collections", collections_path, class: "push-sm-1 btn btn-primary btn-lg" %>
    </div>
  </div>
</div>